### ISSUE TITLE
How to use Flask-CAS along with Flask-Appbuilder?

### ISSUE THREAD

**Issue by Jackeriss** [cameronbwhite/Flask-CAS#44]
I want to add SSO to the Caravel witch is based on Flask-Appbuilder，How to combine them?

**Comment by jstevensfit** [comment]
@Jackeriss I've implemented this you have to edit these three files:

/usr/local/lib/python2.7/dist-packagescaravel/config.py

/usr/local/lib/python2.7/dist-packages/caravel/__init__.py

/usr/local/lib/python2.7/dist-packages/flask_appbuilder/security/views.py

I can shoot you an email with the changes needed or you can wait until later and i'll create a repo and commit the files.

**Comment by Jackeriss** [comment]
@jstevensfit Oh，thank you, you can email me at i@jackeriss.com

**Comment by derek-zl** [comment]
@jstevensfit hi, i also need the code ,can you email me ??? chongchongzl@163.com
